<a href="https://colab.research.google.com/github/fatihonay/Deep-Learning-Journey/blob/main/Pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lists, Arrays, Tensors

We will study basics of tensors with PyTorch for deep learning. Tensors are similar to Numpy arrays which are pretty similar to Python lists.

Unlike Numpy Arrays, Tensors are built to be used with GPU's for Deep Learning.

In [1]:
import torch
import numpy as np

### Lists
The primary role of a list is to hold multiple items in a single variable.
The first item is always at index 0, the second at index 1, etc. Python lists can store mixed data types (integers, strings, objects, and even other lists) together.

In [7]:
odd_list = [1,3,5,7,9]
even_list = [0,2,4,6,8]

even_list

[0, 2, 4, 6, 8]

### Arrays

Numpyy arrays are specialized data structures designed for scientific computing and high-performance data analysis. The most critical role of a NumPy array is vectorization. This allows to perform mathematical operations on entire arrays at once without writing loops.

In [10]:
array_rand = np.random.rand(5,4)
array_rand

array([[0.21836471, 0.70680039, 0.69777721, 0.45776105],
       [0.83415391, 0.14929995, 0.52588778, 0.13070698],
       [0.53929718, 0.70926685, 0.18696516, 0.14905519],
       [0.89907419, 0.08066586, 0.0532394 , 0.16649056],
       [0.40505794, 0.34605342, 0.33490479, 0.66936033]])

Let's check data type

In [13]:
print(array_rand.dtype)

float64


### Tensors

In the context of Python and data science, Tensors are the next evolution after lists and NumPy arrays. They are the fundamental data structure used in Deep Learning frameworks. NumPy arrays live on the CPU but Tensors can be moved to the GPU. And this increase processing speed dramatically for training deep learning models.


In [14]:
tensor_rand = torch.rand(5,4)
tensor_rand

tensor([[0.6082, 0.1166, 0.9145, 0.4526],
        [0.5808, 0.4700, 0.0685, 0.4621],
        [0.8413, 0.6169, 0.7149, 0.1722],
        [0.3400, 0.5285, 0.0206, 0.5183],
        [0.1762, 0.9534, 0.7069, 0.4497]])

As you can see, Tensors are Numpy Arrays are so similar. We can also convert Numpy arrays into Tensors.

In [15]:
arra_to_tensor = torch.tensor(array_rand)
arra_to_tensor

tensor([[0.2184, 0.7068, 0.6978, 0.4578],
        [0.8342, 0.1493, 0.5259, 0.1307],
        [0.5393, 0.7093, 0.1870, 0.1491],
        [0.8991, 0.0807, 0.0532, 0.1665],
        [0.4051, 0.3461, 0.3349, 0.6694]], dtype=torch.float64)